{{- if eq .Values.storage.backend "local" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-telemetry
  labels:
    app.kubernetes.io/name: ballast-telemetry-aggregator
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.local.size }}
  {{- if .Values.storage.local.storageClassName }}
  storageClassName: {{ .Values.storage.local.storageClassName | quote }}
  {{- end }}
{{- end }}
